#
# Copyright 2025-2026 NXP
#
# SPDX-License-Identifier: BSD-3-Clause

CONFIG_MCUX_COMPONENT_device.CMSIS=y
CONFIG_MCUX_COMPONENT_device.system=y
CONFIG_MCUX_COMPONENT_device.startup=n

# disable default configs from examples repo, 
# as its a lib build, following default configs are not required.
CONFIG_MCUX_PRJSEG_module.board.boardfile=n
CONFIG_MCUX_PRJSEG_module.board.clock=n
CONFIG_MCUX_PRJSEG_module.board.console_lite=n
CONFIG_MCUX_PRJSEG_module.board.suite=n
CONFIG_MCUX_PRJSEG_module.board.use_board_clock=n
CONFIG_MCUX_HAS_PRJSEG_module.board.pinmux_sel=n
CONFIG_MCUX_HAS_PRJSEG_module.board.peripheral_sel=n
CONFIG_MCUX_HAS_PRJSEG_project.use_hw_app=n

#regression test
CONFIG_MCUX_COMPONENT_middleware.tfm.secure_reg_test_enable=y

#select profile
CONFIG_MCUX_COMPONENT_middleware.tfm.profile_medium=y

#protected-storage secure tests are enabled by default with medium profile.
CONFIG_MCUX_COMPONENT_middleware.tfm.s.test.protected_storage=y
